services:
  db:
    image: postgres:16-alpine
    container_name: green-leaf-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: green_leaf
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: green-leaf-app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/green_leaf?schema=public
      PORT: "3000"
    ports:
      - "3000:3000"

volumes:
  postgres-data:

